version: "3"

services:
  firefox:
    image: jlesage/firefox:v22.10.4
    container_name: firefox
    environment:
      KEEP_APP_RUNNING: 1
    shm_size: 2gb
    ports:
      - 5800:5800
    volumes:
      - ./user.js:/config/profile/user.js
      - ./downloads:/config/downloads
